
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oadb?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-location: classpath:mapper/**/*.xml
logging:
  level:
    root: info
    web: trace
    org.lwl.demo: debug
pagehepler:
  # 分页合理化 访问0页回到第一页 访问15页回到10页
  reasonable: true
  helper-dialect: mysql

#自定义配置
oa:
  token:
    #单位 : 秒
    expire-time: 99999999
  anonurls: #无需登录直接访问
    - /security/login
    - /t
    - /res/** #ant样式
server:
  port: 9999